galleries:
    pattern:  /
    defaults: { _controller: ClickGallery:Gallery:index }
    
gallery:
    pattern:  /gallery
    defaults: { _controller: ClickGallery:Gallery:gallery }
    
upload:
    pattern:  /upload
    defaults: { _controller: ClickGallery:Photo:upload }
