Click\GalleryBundle\Entity\Photo:
    type: entity
    table: photo
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
