Click\GalleryBundle\Entity\Gallery:
    type: entity
    table: gallery
    repositoryClass: Click\GalleryBundle\Entity\GalleryRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
